### ISSUE TITLE
sickrage sur yunohost

### ISSUE THREAD

**Issue by benhouf** [Antexa/sickrage_ynh#1]
Bonjour, / hello 

Je vais exposer mon problème en francais et je traduirai après.
I will explain my problem in french and after I will translate.

Merci deja pour ton Sickbeard sur Yunohost il m'a été très utile mais Sickbeard a des problemes d'actualisation des téléchargements. J'ai donc essayé d'intaller Sickrage ( https://github.com/SiCKRAGETV/SickRage ) de la même façon mais cela ne marche pas : 502 Bad Gateway. 

/Thank you already for your Sickbeard on yunohost it was very useful but Sickbeard has downloads refresh problems. So I tried to install Sickrage (https://github.com/SiCKRAGETV/SickRage) in the same way but it does not work: 502 Bad Gateway.

est-ce possible ?
is it possible ?

Aurais-tu une solution ? 
Would you have a solution?

Encore merci de ton travail.
Again thank you for your work.

**Comment by Antexa** [comment]
Salut Benhouf, 

J'ai merge les différents scripts pour qu'ils soient compatible avec Sickrage. 

Merci de me faire un retour si tu as un quelconque avec l'installation.

**Comment by benhouf** [comment]
Merci pour ta réactivité ! 

Tout fonctionne parfaitement ! 

Merci encore...
